        <x-footer-items>
          France
        </x-footer-items>
        <x-footer-items>
          Germany
        </x-footer-items>
        <x-footer-items>
          italy
        </x-footer-items>
        <x-footer-items>
          Denmark
        </x-footer-items>
